### ISSUE TITLE
Problem with using macros of inactive windows

### ISSUE THREAD

**Issue by ghost** [martinohanlon/pico-rgbkeypad#2]
Hi,

thank you so much for the code and explanation, I managed to mostly modify it to make it work as a very simple macro keyboard for OBS and Zoom for me.

One issue I have is that when I want to switch scenes in OBS (I have two buttons on the keypad assigned to this) it works flawlessly when OBS is my active window, but when I have Zoom open in the foreground, it becomes very random when I hit the buttons. Zoom doesn't use the hotkeys I use for OBS and this also happens with other apps like Chrome. It does work, but I might have to hit the keys 10 times to activate the key function or maybe it works 3 times in a row without a problem. 

I also have a button for muting my mic in Zoom and (inelegantly) another one to unmute me. I haven't figured out a good way to have the mute button light up when I am muted and switch the led off when i click the key again to unmute myself. Here I have a similar issue where I click the button and it somehow activates the key press multiple times at once. 

I have next to zero experience with Python, just learning it now, so what is wrong in the code? I just paste the modified bit below (instead of your hid_keyboard.py).

```
> keypad = RGBKeypad()
> kbd = Keyboard(usb_hid.devices)
> 
> key0 = keypad[0, 0]
> key1 = keypad[1, 0]
> key2 = keypad[2, 0]
> key3 = keypad[3, 0]
> key4 = keypad[0, 1]
> key5 = keypad[1, 1]
> key6 = keypad[2, 1]
> key7 = keypad[3, 1]
> key8 = keypad[0, 2]
> key9 = keypad[1, 2]
> keyA = keypad[2, 2]
> keyB = keypad[3, 2]
> keyC = keypad[0, 3]
> keyD = keypad[1, 3]
> keyE = keypad[2, 3]
> keyF = keypad[3, 3]
> 
> key3.color = (255, 100, 50)
> key3.brightness = 0.2
> 
> while True:
>     if key3.is_pressed():
>        keypad.clear()
>        key3.color = (255, 100, 50)
>     if keyC.is_pressed():
>        kbd.send(Keycode.CONTROL, Keycode.SHIFT, Keycode.NINE)
>        keyD.clear()
>        keyC.color = (60, 220, 240)
>     if keyD.is_pressed():
>        kbd.send(Keycode.CONTROL, Keycode.SHIFT, Keycode.EIGHT)
>        keyC.clear()
>        keyD.color = (60, 220, 240)
>     if keyF.is_pressed():
>        kbd.send(Keycode.ALT, Keycode.A)
>        keyF.color = (155, 120, 255)
```

Any help at all would be much appreciated! Thank you.

edited to add code tags

**Comment by martinohanlon** [comment]
One thing which jumps out is that the program isnt waiting for the key to be released before continuing the loop.

This will result in the same key press being sent MANY times. It equivalent of continously tapping the same key on the keyboard but VERY quickly.

e.g.

This code will result in CTRL + SHIFT + NINE being sent multiple times for as long as your finger is pushing button keyC. Who knows what the operating system/running applications will do with this?!

```
while True:
    if keyC.is_pressed():
       kbd.send(Keycode.CONTROL, Keycode.SHIFT, Keycode.NINE)
       keyD.clear()
       keyC.color = (60, 220, 240)
```

I would try adding some code to wait until the key is released. e.g.

```
while True:
    if keyC.is_pressed():
       kbd.send(Keycode.CONTROL, Keycode.SHIFT, Keycode.NINE)
       keyD.clear()
       keyC.color = (60, 220, 240)
       # wait for the key to be released
       while keyC.is_pressed():
           pass
```

**Comment by martinohanlon** [comment]
Closing the issue as this is not an issue with rgbkeypad.

**Comment by martinohanlon** [comment]
@timoschrader88 you might want to have a look at this example where this approach is used - https://github.com/martinohanlon/pico-rgbkeypad/blob/main/examples/hid_keyboard.py

**Comment by ghost** [comment]
I did use that example to begin with but I encountered the same issue that I encounter now where if I use the "while key is pressed and pass" commands, the button press sometimes just isn't registering, even in OBS (I suppose my modification where it basically executes the key press many times was a bit of redundancy that at least made sure the key press registeres right away).

Still, if I don't have OBS as the active window on screen, the button presses don't register when they should. After all, the actual keyboard hotkey combination works flawlessly. I very much assume something is wrong with the way I have organized the code but all I am trying to do is press button x, have it light up and execute a macro to switch an OBS scene, and then stay lit until I hit button y to switch to a different scene, at which point it also clears the color of button x. 

I can fiddle around with the code for the most part myself using helpful examples like yours, but I can't comprehend why OBS won't register key presses consitently with the pass command or why it generally barely registers key presses when OBS is not the active window.

I don't know if you know why this is happening, but in any case thank you so much for your help and I am really enjoying the keypad and experimenting with the code so far!

**Comment by martinohanlon** [comment]
In which case it may not be anything to do with your program. All the code is doing is acting as a keyboard. Do you have the same issue when using an "actual" keyboard? It could be that "something", OBS, zoom, another application is trapping the keyboard events.

**Comment by ghost** [comment]
That's the thing, the actual keyboard combo works flawlessly with OBS active, or any other program in the foreground. Nothing weird happens and OBS scenes just switch instantly as they should. Very strange.
